spring.application.name=terba7 back-end


# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/terba7_db
spring.datasource.username=postgres
spring.datasource.password=terba7admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080


# Security temporaire
spring.security.user.name=admin
spring.security.user.password=admin123